spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gestion_erp_test}
    username: ${DB_USERNAME:gestion_test}
    password: ${DB_PASSWORD:gestion_test}
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.daboerp.gestion: DEBUG
