spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/gestion_erp
  jpa:
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': true

logging:
  level:
    com.daboerp.gestion: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
